/**
 * electron-builder configuration (moved out of package.json "build" so the
 * auto-update feed URL can be injected at build time instead of living in
 * the repo).
 *
 * REVELITH_UPDATE_URL : public base URL of the update channel (the generic
 * provider prefix that serves latest.yml / latest-mac.yml). Required for
 * release builds; CI provides it as a repository secret. For local release
 * builds put it in apps/shell/electron-builder.env (gitignored) : the
 * electron-builder CLI loads that file automatically.
 *
 * When the variable is unset (forks, PR smoke builds, plain local packaging)
 * the publish config is omitted: electron-builder then bakes no
 * app-update.yml into the app and in-app auto-update stays disabled.
 */

const { existsSync } = require('node:fs')
const { join } = require('node:path')

const updateUrl = process.env.REVELITH_UPDATE_URL

// REVELITH_MAC_X64=1 : opt into packaging the Intel (x64) dmg/zip alongside
// arm64. Off by default: Intel packages must only ever ship signed with the
// company certificate (planned dual-track pipeline), so the current release
// pipeline stays arm64-only and never produces a personally-signed Intel
// artifact. The downstream layout (feed archive name, Revelith-intel.dmg
// alias) keys off which dmgs exist, so flipping this flag is the single
// switch.
const includeMacX64 = process.env.REVELITH_MAC_X64 === '1'

// LICENSES.chromium.html only exists after the Electron binary download :
// since Electron 42 that no longer happens during `npm ci` (the postinstall
// script was replaced by the lazy `install-electron` bin), and electron-builder
// exits 0 on a missing extraResources source, so without this check the
// installer would silently ship without the Chromium license.
for (const rel of [
  '../../node_modules/ws',
  '../../node_modules/electron/dist/LICENSES.chromium.html',
  '../../node_modules/@embedpdf/pdfium/dist/pdfium.wasm',
  '../pdf/node_modules/harfbuzzjs/hb-subset.wasm',
]) {
  if (!existsSync(join(__dirname, rel))) {
    throw new Error(
      `electron-builder extraResources source missing: ${rel} (npm hoisting changed?)`,
    )
  }
}

/** @type {import('electron-builder').Configuration} */
const config = {
  appId: 'com.revelith.app',
  productName: 'ReveLith',
  // Resolved from the installed electron package so dependency bumps can
  // never leave a stale hard-coded pin behind (packaging would silently ship
  // the old runtime).
  electronVersion: require('electron/package.json').version,
  directories: {
    output: 'release',
  },
  files: ['out/**'],
  extraResources: [
    {
      from: 'build/THIRD-PARTY-NOTICES.txt',
      to: 'THIRD-PARTY-NOTICES.txt',
    },
    {
      from: '../../node_modules/electron/dist/LICENSES.chromium.html',
      to: 'LICENSES.chromium.html',
    },
    {
      from: '../docs/out',
      to: 'modules/docs',
    },
    {
      from: '../sheets/out',
      to: 'modules/sheets',
    },
    {
      from: '../slides/out',
      to: 'modules/slides',
    },
    {
      from: '../pdf/out',
      to: 'modules/pdf',
    },
    {
      from: '../markdown/out',
      to: 'modules/markdown',
    },
    {
      from: '../html/out',
      to: 'modules/html',
    },
    // PDF text editing engines: the bundled main resolves these under
    // Resources/wasm when node_modules is absent (apps/pdf/src/main/wasm-path.ts)
    {
      from: '../../node_modules/@embedpdf/pdfium/dist/pdfium.wasm',
      to: 'wasm/pdfium.wasm',
    },
    {
      from: '../pdf/node_modules/harfbuzzjs/hb-subset.wasm',
      to: 'wasm/hb-subset.wasm',
    },
  ],
  // `mimeType` is read only by the Linux target, where it becomes the
  // desktop entry's MimeType= list; associations without it are dropped
  // there. macOS and Windows ignore the field and key off `ext`.
  // `icon` gives each type its own OS icon (build/icons, generated by
  // `node build/gen-doc-icons.mjs`): DefaultIcon on Windows/macOS instead of
  // the generic app icon.
  fileAssociations: [
    {
      ext: 'docx',
      name: 'Word Document',
      role: 'Editor',
      icon: 'build/icons/docx.ico',
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    },
    {
      ext: 'xlsx',
      name: 'Excel Workbook',
      role: 'Editor',
      icon: 'build/icons/xlsx.ico',
      mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    },
    {
      ext: 'pptx',
      name: 'PowerPoint Presentation',
      role: 'Editor',
      icon: 'build/icons/pptx.ico',
      mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    },
    {
      ext: 'xls',
      name: 'Excel 97-2003 Workbook',
      role: 'Editor',
      icon: 'build/icons/xlsx.ico',
      mimeType: 'application/vnd.ms-excel',
    },
    {
      ext: 'csv',
      name: 'CSV Document',
      role: 'Editor',
      icon: 'build/icons/xlsx.ico',
      mimeType: 'text/csv',
    },
    {
      ext: 'pdf',
      name: 'PDF Document',
      role: 'Editor',
      icon: 'build/icons/pdf.ico',
      mimeType: 'application/pdf',
    },
    {
      ext: 'md',
      name: 'Markdown Document',
      role: 'Editor',
      icon: 'build/icons/md.ico',
      mimeType: 'text/markdown',
    },
    {
      ext: 'markdown',
      name: 'Markdown Document',
      role: 'Editor',
      icon: 'build/icons/md.ico',
      mimeType: 'text/markdown',
    },
  ],
  npmRebuild: false,
  mac: {
    // Two separate arch packages (NOT universal): arm64 keeps the exact
    // artifact names and update-feed entries it always had, x64 (opt-in via
    // REVELITH_MAC_X64=1, see includeMacX64 above) adds Intel support with
    // electron-builder's default arch-less names (Revelith-<v>.dmg /
    // Revelith-<v>-mac.zip). Both zips land in one latest-mac.yml and
    // electron-updater picks by process.arch. Dual-arch packs ship the same
    // lipo fat xlsx-sidecar.
    target: [
      { target: 'dmg', arch: includeMacX64 ? ['arm64', 'x64'] : ['arm64'] },
      { target: 'zip', arch: includeMacX64 ? ['arm64', 'x64'] : ['arm64'] },
    ],
    category: 'public.app-category.productivity',
    hardenedRuntime: true,
    gatekeeperAssess: false,
    entitlements: 'build/entitlements.mac.plist',
    entitlementsInherit: 'build/entitlements.mac.plist',
    notarize: true,
    extraResources: [
      {
        from: '../sheets/native/xlsx-engine/target/release/xlsx-sidecar',
        to: 'native/xlsx-sidecar',
      },
    ],
  },
  win: {
    target: [
      {
        target: 'nsis',
        arch: ['x64', 'arm64'],
      },
    ],
    // Authenticode signing is env-driven so unsigned local/CI smoke builds
    // keep working: set CSC_LINK (+CSC_KEY_PASSWORD) for a PFX, or the
    // AZURE_* vars for Azure Trusted Signing. CI decodes CSC_LINK_B64 into
    // $RUNNER_TEMP/cert.pfx (see .github/workflows/release.yml).
    // (electron-builder >=26.15 schema: cscLink/cscKeyPassword live on the
    // win block; the timestamp server lives in signtoolOptions.)
    ...(process.env.CSC_LINK ? { cscLink: process.env.CSC_LINK } : {}),
    ...(process.env.CSC_KEY_PASSWORD ? { cscKeyPassword: process.env.CSC_KEY_PASSWORD } : {}),
    ...(process.env.AZURE_TRUSTED_SIGNING_ENDPOINT
      ? {
          azureSignOptions: {
            endpoint: process.env.AZURE_TRUSTED_SIGNING_ENDPOINT,
            codeSigningAccountName: process.env.AZURE_CODE_SIGNING_ACCOUNT,
            certificateProfileName: process.env.AZURE_CERTIFICATE_PROFILE,
          },
        }
      : {}),
    // helper exes, uninstaller and the main exe all get the timestamped
    // signature (DLLs are signed by default whenever signing is enabled)
    signAndEditExecutable: true,
    signtoolOptions: {
      rfc3161TimeStampServer: 'http://timestamp.digicert.com',
    },
    extraResources: [
      {
        from: existsSync(
          join(
            __dirname,
            '../sheets/native/xlsx-engine/target/aarch64-pc-windows-msvc/release/xlsx-sidecar.exe',
          ),
        )
          ? '../sheets/native/xlsx-engine/target/aarch64-pc-windows-msvc/release/xlsx-sidecar.exe'
          : existsSync(
                join(
                  __dirname,
                  '../sheets/native/xlsx-engine/target/x86_64-pc-windows-gnu/release/xlsx-sidecar.exe',
                ),
              )
            ? '../sheets/native/xlsx-engine/target/x86_64-pc-windows-gnu/release/xlsx-sidecar.exe'
            : '../sheets/native/xlsx-engine/target/release/xlsx-sidecar.exe',
        to: 'native/xlsx-sidecar.exe',
      },
    ],
  },
  // Unlike win (which cross-compiles the sidecar to an explicit target
  // triple), linux takes it from cargo's host-native target/release/ : the
  // same source mac uses. So no `arch` is pinned here: electron-builder
  // defaults to the build host's architecture, which is the only one the
  // sidecar was actually built for. Packaging arm64 on an x64 host, or the
  // reverse, needs a matching `cargo build --target` first.
  linux: {
    // AppImage (self-contained, any distro) + deb (apt install, pulls in the
    // GTK/NSS runtime deps) + rpm (dnf/zypper install on Fedora / RHEL /
    // openSUSE). Default artifact names are kept on purpose :
    // Revelith-<v>.AppImage / revelith_<v>_amd64.deb : because the public
    // README download links and the already-published linux-v0.5.149 release
    // use them.
    target: [
      { target: 'AppImage', arch: ['x64'] },
      { target: 'deb', arch: ['x64'] },
      { target: 'rpm', arch: ['x64'] },
    ],
    // deb control metadata; values match the manually published 0.5.149 deb
    // so apt sees the new packages as the same lineage. Homepage comes from
    // package.json "homepage"; the Package field is pinned in the deb block
    // below (packageName is a per-target option, rejected here by the schema).
    maintainer: 'ReveLith',
    vendor: 'ReveLith',
    category: 'Office',
    icon: 'build/icon.png',
    // mac and win name the binary from productName; linux instead derives it
    // from package.json "name", and "@revelith/shell" sanitizes to the
    // invalid "@revelithshell". Setting it explicitly also makes the
    // generated revelith.desktop match the WM_CLASS Electron reports (it
    // takes that from the executable basename), so the running window links
    // back to its launcher entry.
    executableName: 'revelith',
    // Electron takes its X11 app_id from package.json "desktopName"
    // (revelith.desktop); syncDesktopName makes electron-builder name the
    // .desktop file and its StartupWMClass from the same value. Without it
    // StartupWMClass falls back to productName ("Revelith"), which does not
    // match the "revelith" WM_CLASS the window actually reports : and X11
    // compares case-sensitively, so the taskbar shows an unlinked window.
    syncDesktopName: true,
    extraResources: [
      {
        from: '../sheets/native/xlsx-engine/target/release/xlsx-sidecar',
        to: 'native/xlsx-sidecar',
      },
    ],
  },
  // Same "@revelith/shell" problem as executableName above: the default deb
  // artifact name derives from package.json "name", and the scope's "/" makes
  // fpm treat "@revelith" as a directory. Spell the published name out
  // (revelith_<version>_amd64.deb, matching the linux-v0.5.149 release).
  // packageName pins the control Package field to the same value the 0.5.149
  // deb shipped with : apt treats a different Package name as an unrelated
  // install, breaking upgrades. Without it, fpm receives productName
  // "Revelith" and only happens to downcase it to the right value.
  deb: {
    artifactName: 'ReveLith_${version}_${arch}.deb',
    packageName: 'revelith',
  },
  // Same "@revelith/shell" naming problem as deb: spell the artifact name
  // out (${arch} expands to the rpm arch string, x86_64) and pin the rpm
  // Package name so dnf/zypper treat successive releases as upgrades of the
  // same package. Like deb, rpm installs run no in-app updater : users
  // upgrade with `dnf install ./<new>.rpm`. Packaging needs rpmbuild on the
  // build host (the `rpm` apt package on Ubuntu; CI installs it).
  //
  // publish: null (explicit) keeps the rpm out of the electron-updater feed
  // and off the CDN entirely: the rpm is a GitHub-Release download only, so
  // latest-linux.yml keeps listing exactly what the CDN pipeline uploads
  // (AppImage + deb) and the promote workflow needs no rpm alias.
  rpm: {
    artifactName: 'ReveLith-${version}.${arch}.rpm',
    packageName: 'revelith',
    publish: null,
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    installerIcon: 'build/icon.ico',
    uninstallerIcon: 'build/icon.ico',
    installerHeaderIcon: 'build/icon.ico',
    // Explorer "Open with ReveLith" verbs (customInstall/customUnInstall);
    // the ext list inside must stay in sync with fileAssociations above.
    include: 'build/installer.nsh',
  },
  dmg: {
    sign: true,
    icon: 'build/icon-mac.png',
  },
  afterAllArtifactBuild: 'build/notarize-dmg.js',
}

config.publish = updateUrl
  ? [
      {
        provider: 'generic',
        url: updateUrl.replace(/\/+$/, ''),
        channel: 'latest',
      },
    ]
  : [
      {
        provider: 'github',
        owner: 'sainibhaowal',
        repo: 'ReveLith',
        releaseType: 'release',
      },
    ]

module.exports = config
