import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

/**
 * Per-document-type OS icons (apps/shell/build/icons, generated by
 * `node build/gen-doc-icons.mjs`): validates the committed artifacts and the
 * packager wiring that consumes them.
 */

const SHELL_DIR = fileURLToPath(new URL('..', import.meta.url))
const ICONS_DIR = `${SHELL_DIR}/build/icons`

function runGeneratorCheck(): string {
  return execFileSync('node', [`${SHELL_DIR}/build/gen-doc-icons.mjs`, '--check'], {
    encoding: 'utf8',
  })
}

describe('doc icon artifacts', () => {
  it('every document type has .ico/.icns/.png artifacts', () => {
    for (const name of ['docx', 'xlsx', 'pptx', 'pdf', 'md', 'html']) {
      for (const ext of ['ico', 'icns', 'png']) {
        expect(existsSync(`${ICONS_DIR}/${name}.${ext}`), `${name}.${ext}`).toBe(true)
      }
    }
  })

  it('the generator self-validation passes on the committed files', () => {
    const out = runGeneratorCheck()
    const report = JSON.parse(out) as Record<string, { ico: number[]; icns: string[] }>
    expect(Object.keys(report).sort()).toEqual(['docx', 'html', 'md', 'pdf', 'pptx', 'xlsx'])
    for (const [name, entry] of Object.entries(report)) {
      // ICO carries 16/32/48/256px PNG entries; ICNS carries ic07/ic08
      expect(entry.ico, `${name} ico sizes`).toEqual([16, 32, 48, 256])
      expect(entry.icns, `${name} icns elements`).toEqual(['ic08', 'ic07'])
    }
  })

  it('icons are distinct per type (no copy-paste duplicates)', () => {
    const hashes = new Set<string>()
    for (const name of ['docx', 'xlsx', 'pptx', 'pdf', 'md', 'html']) {
      const png = readFileSync(`${ICONS_DIR}/${name}.png`)
      // compare pixels, not container bytes (timestamps could differ)
      const idat = png.subarray(png.indexOf(Buffer.from('IDAT')) + 8)
      const key = idat.toString('base64')
      expect(hashes.has(key), `${name} icon duplicates another`).toBe(false)
      hashes.add(key)
    }
  })
})

describe('packager wiring', () => {
  it('every fileAssociation has a per-type icon that exists on disk', () => {
    const config = readFileSync(`${SHELL_DIR}/electron-builder.cjs`, 'utf8')
    // fileAssociations name the icon (icon: 'docx'); electron-builder resolves
    // that against build/icons/<name>.ico rather than taking a path.
    const entries = [...config.matchAll(/ext: '([^']+)'[\s\S]*?icon: '([^']+)'/g)].map((m) => ({
      ext: m[1],
      icon: m[2],
    }))
    expect(entries.length).toBeGreaterThanOrEqual(8)
    for (const { ext, icon } of entries) {
      expect(icon, `${ext} icon name`).toMatch(/^[a-z]+$/)
      const relative = `build/icons/${icon}.ico`
      expect(existsSync(`${SHELL_DIR}/${relative}`), `${ext} icon file (${relative})`).toBe(true)
    }
  })

  it('windows signing is opt-in and unsigned builds keep working', () => {
    const config = readFileSync(`${SHELL_DIR}/electron-builder.cjs`, 'utf8')
    // Signing moved off the old CSC_LINK / AZURE_* env-var contract onto
    // REVELITH_WIN_SIGN_MODE, which delegates to scripts/win-sign.cjs for every
    // binary electron-builder signs. Unset (local and fork builds) must leave
    // the config with no signing block so packaging stays unsigned.
    for (const key of [
      'REVELITH_WIN_SIGN_MODE',
      'win-sign.cjs',
      'signingHashAlgorithms',
      'signtoolOptions',
    ]) {
      expect(config, key).toContain(key)
    }
    // The hook must exist or every signed build crashes with ENOENT.
    expect(existsSync(`${SHELL_DIR}/../../scripts/win-sign.cjs`), 'scripts/win-sign.cjs').toBe(true)
    // The retired env-var contract must not creep back in.
    for (const retired of [
      'CSC_LINK',
      'AZURE_TRUSTED_SIGNING_ENDPOINT',
      'timestamp.digicert.com',
    ]) {
      expect(config, retired).not.toContain(retired)
    }
  })
})
